define({
    "submitComment": "Poster",
    "cancel": "Annuler",
    "validate": "Valider",
    "comments": "Commentaires",
    "addComment": "Ajouter un commentaire",
    "anyComment": "un commentaire ?",
    "authorHint": "votre nom ici...",
    "commentHint": "votre commentaire ici ...",
    "dateFormat": "D MMMM YYYY",
    "dateTimeFormat": "le DD/MM/YYYY à HH\\hmm",
    "picturesToComment": "photos à commenter.",
    "enterDescription": "une description ?",
    "addDescription": "double clique pour ajouter une description",
    "uploadTitle": "Ajouter des photos",
    "uploadVideoTitle": "Ajouter une vidéo",
    "uploadPictures": "Charger les photos",
    "uploadVideo": "Charger les vidéos",
    "videoUrlPlaceholder": "L'URL de votre vidéo ici",
    "deletePicture": "Supprimer cette photo",
    "confirmDeletePicture": "Etes-vous sûr de vouloir supprimer cette photo ?",
    "newUser": "Bienvenue sur votre blog photo !",
    "email": "Email",
    "password": "Mot de passe",
    "repeatPassword": "Confirmation",
    "infoNewUser": "Vous devez créer un compte pour pouvoir charger des images sur le site, modérer les commentaires et modifier vos photos.",
    "passwordsNotIdenticals": "la confirmation doit être identique au mot de passe",
    "emailError": "l'email n'est pas valide",
    "video-dailymotion": "DailyMotion",
    "video-youtube": "Youtube",
    "video-vimeo": "Vimeo",
    "filter": "Filtrer..."
});