define({
    "root": {
        "submitComment": "OK",
        "cancel": "Cancel",
        "validate": "OK",
        "comments": "Comments",
        "addComment": "Add comment",
        "anyComment": "any comment ?",
        "authorHint": "your name here...",
        "commentHint": "your comment here...",
        "dateFormat": "MMMM DD YYYY",
        "dateTimeFormat": "MM/DD/YYYY, HH:mm",
        "picturesToComment": "pictures to comment.",
        "enterDescription": "enter a description...",
        "addDescription": "double click to add a description",
        "uploadTitle": "Add pictures",
        "uploadVideoTitle": "Add video",
        "uploadPictures": "Upload",
        "uploadVideo": "Upload",
        "videoUrlPlaceholder": "Please paste the URL of your video here",
        "deletePicture": "Delete this picture",
        "confirmDeletePicture": "Are you sure you want to delete this picture ?",
        "newUser": "Welcome to your WallBlog !",
        "email": "Email",
        "password": "Password",
        "repeatPassword": "Repeat password",
        "infoNewUser": "",
        "passwordsNotIdenticals": "passwords are not the same",
        "emailError": "email is not valid",
        "video-dailymotion": "DailyMotion",
        "video-youtube": "Youtube",
        "video-vimeo": "Vimeo",
        "filter": "Filter..."
    },
    "fr": true
});