define({
    "root": {
        "submitComment": "OK",
        "cancel": "Cancel",
        "validate": "OK",
        "comments": "Comments",
        "addComment": "Add comment",
        "anyComment": "any comment ?",
        "authorHint": "your name here...",
        "commentHint": "your comment here...",
        "dateFormat": "MMMM DD YYYY",
        "dateTimeFormat": "MM/DD/YYYY, HH:mm",
        "picturesToClickAndComment": "pictures : click & comment.",
        "enterDescription": "enter a description...",
        "addDescription": "double click to add a description",
        "uploadTitle": "Add pictures",
        "uploadVideoTitle": "Add video",
        "uploadPictures": "Upload",
        "uploadVideo": "Upload",
        "deletePicture": "Delete this picture",
        "confirmDeletePicture": "Are you sure you want to delete this picture ?",
        "newUser": "Welcome to your WallBlog !",
        "email": "Email",
        "password": "Password",
        "repeatPassword": "Repeat password",
        "infoNewUser": "",
        "passwordsNotIdenticals": "passwords are not the same",
        "emailError": "email is not valid",
        "video-webm": "WebM",
        "video-ogv": "Ogg Vorbis",
        "video-mp4": "MP4"
    },
    "fr": true
});